version: "3.8"

services:
  # Frontend Development Server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_MOCK_EMAIL=true
      - VITE_DEBUG_MODE=true
    depends_on:
      - backend
    networks:
      - peptok-network

  # Backend API Server (Optional - app works with mock data)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=your-dev-jwt-secret-key
      - CORS_ORIGIN=http://localhost:8080
    networks:
      - peptok-network

  # PostgreSQL Database (Optional)
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=peptok_dev
      - POSTGRES_USER=peptok_user
      - POSTGRES_PASSWORD=peptok_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - peptok-network

networks:
  peptok-network:
    driver: bridge

volumes:
  postgres_data:
