services:
  # Development backend with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/package.json:/app/package.json:ro
      - backend-node-modules:/app/node_modules
    command: npm run dev

  # Development frontend with hot reload
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_URL=http://localhost:3001/api
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./index.html:/app/index.html:ro
      - ./package.json:/app/package.json:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./tailwind.config.ts:/app/tailwind.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - frontend-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev -- --host 0.0.0.0

volumes:
  backend-node-modules:
  frontend-node-modules:
